---
# Copyright 2016, AT&T, and it's Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: check for bootstrap
  shell: kubectl get nodes
  register: kube_bootstrap
  failed_when: false
  ignore_errors: true

- name: debug bootstrap output
  debug: msg="{{ kube_bootstrap }}"

- name: collect api endpoint from masters
  shell: ip addr show {{ public_iface }} | grep "inet\b" | head -n 1 | awk '{print $2}' | cut -d/ -f1
  register: kube_api_endpoint

- name: kubernetes master api endpoints
  debug: msg={{ kube_api_endpoint.stdout }}

- name: initialize the kubernetes master
  shell: "kubeadm init --token {{ init_token }} --use-kubernetes-version {{ kube_version }} --api-advertise-addresses {{ kube_api_endpoint.stdout }}"
  when: "'localhost:8080 was refused' in kube_bootstrap.stderr and kube_sdn != 'flannel'"
  register: initout
  ignore_errors: true

# The pod network CIDR is hardcoded in the reference flannel CNI templates
- name: initialize the kubernetes master for flannel
  shell: "kubeadm init --token {{ init_token }} --use-kubernetes-version {{ kube_version }} --api-advertise-addresses {{ kube_api_endpoint.stdout }} --pod-network-cidr={{ kube_cluster_ip_cidr }}"
  when: "'localhost:8080 was refused' in kube_bootstrap.stderr and kube_sdn == 'flannel'"
  register: initout
  ignore_errors: true

- name: check kubectl after initializing the kubernetes master
  shell: kubectl get nodes
  register: kube_bootstrap
  ignore_errors: true

- name: debug kubectl output
  debug: msg="{{ kube_bootstrap }}"

# BELOW ARE TWO DEBUGGING OPTIONS:
#- name: debug kubernetes init output
#  debug: msg="{{ initout }}"

#- name: printing initialization output for user
#  debug: msg="{{ initout.stdout }}"
#  ignore_errors: true
