---
# Copyright 2016, JinkIT, and it's Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: check for bootstrap
  shell: kubectl get nodes
  register: kube_bootstrap
  ignore_errors: true

- name: debug bootstrap output
  debug: msg="{{ kube_bootstrap }}"

- name: collect api endpoint from masters
  shell: ip addr show {{ public_iface }} | grep "inet\b" | awk '{print $2}' | cut -d/ -f1
  register: kube_api_endpoint

- name: kubernetes master api endpoints
  debug: msg={{ kube_api_endpoint.stdout }}

- name: initialize the kubernetes master
  shell: "kubeadm init --token {{ init_token }} --api-advertise-addresses {{ kube_api_endpoint.stdout }}"
  when: "'localhost:8080 was refused' in kube_bootstrap.stderr"
  register: initout
  ignore_errors: true

# BELOW ARE TWO DEBUGGING OPTIONS:
#- name: debug kubernetes init output
#  debug: msg="{{ initout }}"

#- name: printing initialization output for user
#  debug: msg="{{ initout.stdout }}"
#  ignore_errors: true
